### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by srnyx** [NucleoidMC/anonymize#8]

**Comment by haykam821** [comment]
Looks like this is just a matter of updating the dependency:

https://github.com/NucleoidMC/anonymize/blob/96596cbe79c37ed730d4f6a9997bb69b86050cf3/src/main/resources/fabric.mod.json#L24

You can use Fabric loader's [dependency overrides](https://fabricmc.net/wiki/tutorial:dependency_overrides) for now.
